//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace US5NET.Models.US
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class T_SYST_CLAS
    {
        [DisplayName("系統代號")]
        public string SYST_NO { get; set; }
        [DisplayName("序號")]
        public string CLAS_NO { get; set; }
        [DisplayName("分類名稱")]
        public string CLAS_NAME { get; set; }
    }
}
