//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace US5NET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CASE_BASE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_CASE_BASE()
        {
            this.T_ANSR_DATA = new HashSet<T_ANSR_DATA>();
            this.T_ANSR_FILE = new HashSet<T_ANSR_FILE>();
            this.T_QUER_DATA = new HashSet<T_QUER_DATA>();
            this.T_QUER_FILE = new HashSet<T_QUER_FILE>();
        }
    
        public string CASE_NO { get; set; }
        public string SYST_NO { get; set; }
        public string CLAS_NO { get; set; }
        public string EMPL_NO { get; set; }
        public string CASE_STAR_DATE { get; set; }
        public string CASE_END_DATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_ANSR_DATA> T_ANSR_DATA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_ANSR_FILE> T_ANSR_FILE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_QUER_DATA> T_QUER_DATA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_QUER_FILE> T_QUER_FILE { get; set; }
    }
}
